<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	"Expiration Date" => array(
		__( "Expiration Date", 'yith-woocommerce-membership' ),
	),
	"Status" => array(
		__( "Status", 'yith-woocommerce-membership' ),
	),
	"Default" => array(
		__( "Default", 'yith-woocommerce-membership' ),
	),
	"Hide alternative content" => array(
		__( "Hide alternative content", 'yith-woocommerce-membership' ),
	),
	"Membership" => array(
		__( "Membership", 'yith-woocommerce-membership' ),
	),
	"Member" => array(
		__( "Member", 'yith-woocommerce-membership' ),
	),
	"Product" => array(
		__( "Product", 'yith-woocommerce-membership' ),
	),
	"Download" => array(
		__( "Download", 'yith-woocommerce-membership' ),
	),
	"Linked text" => array(
		__( "Linked text", 'yith-woocommerce-membership' ),
	),
	"Membership History" => array(
		__( "Membership History", 'yith-woocommerce-membership' ),
	),
	"Search Membership Plans" => array(
		__( "Search Membership Plans", 'yith-woocommerce-membership' ),
	),
	"Please enter %d or more characters" => array(
		__( "Please enter %d or more characters", 'yith-woocommerce-membership' ),
	),
	"Searching..." => array(
		__( "Searching...", 'yith-woocommerce-membership' ),
	),
	"No results found" => array(
		__( "No results found", 'yith-woocommerce-membership' ),
	),
	"Current post" => array(
		__( "Current post", 'yith-woocommerce-membership' ),
	),
	"Post" => array(
		__( "Post", 'yith-woocommerce-membership' ),
	),
	"Page" => array(
		__( "Page", 'yith-woocommerce-membership' ),
	),
	"Membership Protected Links" => array(
		__( "Membership Protected Links", 'yith-woocommerce-membership' ),
	),
	"The selected post has no secure links" => array(
		__( "The selected post has no secure links", 'yith-woocommerce-membership' ),
	),
	"Link class" => array(
		__( "Link class", 'yith-woocommerce-membership' ),
	),
	"Print protected links set into:" => array(
		__( "Print protected links set into:", 'yith-woocommerce-membership' ),
	),
	"Guest" => array(
		__( "Guest", 'yith-woocommerce-membership' ),
	),
	"Non-member" => array(
		__( "Non-member", 'yith-woocommerce-membership' ),
	),
	"Users that can see this block content:" => array(
		__( "Users that can see this block content:", 'yith-woocommerce-membership' ),
	),
	"Open Media Library" => array(
		__( "Open Media Library", 'yith-woocommerce-membership' ),
	),
	"Membership Protected Media" => array(
		__( "Membership Protected Media", 'yith-woocommerce-membership' ),
	),
	"Media URL" => array(
		__( "Media URL", 'yith-woocommerce-membership' ),
	),
	"Starting date" => array(
		__( "Starting date", 'yith-woocommerce-membership' ),
	),
	"All memberships" => array(
		__( "All memberships", 'yith-woocommerce-membership' ),
	),
	"Show" => array(
		__( "Show", 'yith-woocommerce-membership' ),
	),
	"Membership plans to print:" => array(
		__( "Membership plans to print:", 'yith-woocommerce-membership' ),
	),
	"Membership Plan Items" => array(
		__( "Membership Plan Items", 'yith-woocommerce-membership' ),
	),
	"There are no items to show for the selected plan" => array(
		__( "There are no items to show for the selected plan", 'yith-woocommerce-membership' ),
	),
	"Membership Downloaded Product Links" => array(
		__( "Membership Downloaded Product Links", 'yith-woocommerce-membership' ),
	),
	"Print protected media link. Please note: media should be set as protected before printing the link" => array(
		__( "Print protected media link. Please note: media should be set as protected before printing the link", 'yith-woocommerce-membership' ),
	),
	"Print the list of items included in a membership plan" => array(
		__( "Print the list of items included in a membership plan", 'yith-woocommerce-membership' ),
	),
	"Only memberships not associated with a subscription plan" => array(
		__( "Only memberships not associated with a subscription plan", 'yith-woocommerce-membership' ),
	),
	"Only memberships associated with a subscription plan" => array(
		__( "Only memberships associated with a subscription plan", 'yith-woocommerce-membership' ),
	),
	"Print the details of the membership plans joined by the current user" => array(
		__( "Print the details of the membership plans joined by the current user", 'yith-woocommerce-membership' ),
	),
	"Text to show to customers without a membership:" => array(
		__( "Text to show to customers without a membership:", 'yith-woocommerce-membership' ),
	),
	"Print items included in plan:" => array(
		__( "Print items included in plan:", 'yith-woocommerce-membership' ),
	),
	"Membership Protected Content" => array(
		__( "Membership Protected Content", 'yith-woocommerce-membership' ),
	),
	"Show specific content based on the membership plans" => array(
		__( "Show specific content based on the membership plans", 'yith-woocommerce-membership' ),
	),
	"Print the protected links set into a post, page, or product" => array(
		__( "Print the protected links set into a post, page, or product", 'yith-woocommerce-membership' ),
	),
	"Print a table with links to downloaded products" => array(
		__( "Print a table with links to downloaded products", 'yith-woocommerce-membership' ),
	),
	"Choose a specific plan" => array(
		__( "Choose a specific plan", 'yith-woocommerce-membership' ),
	),
	"Alternative content to show:" => array(
		__( "Alternative content to show:", 'yith-woocommerce-membership' ),
	),
	"Hide alternative content or choose which to show in this specific block" => array(
		__( "Hide alternative content or choose which to show in this specific block", 'yith-woocommerce-membership' ),
	),
	"Block titleMembers-only content starts here" => array(
		_x( "Members-only content starts here", "Block title", 'yith-woocommerce-membership' ),
	),
	"Block nameMembers-only content start" => array(
		_x( "Members-only content start", "Block name", 'yith-woocommerce-membership' ),
	),
	"Block nameMembership protected links" => array(
		_x( "Membership protected links", "Block name", 'yith-woocommerce-membership' ),
	),
	"Block nameMembership protected content" => array(
		_x( "Membership protected content", "Block name", 'yith-woocommerce-membership' ),
	),
	"Block nameMembership protected media" => array(
		_x( "Membership protected media", "Block name", 'yith-woocommerce-membership' ),
	),
	"Block nameMembership history" => array(
		_x( "Membership history", "Block name", 'yith-woocommerce-membership' ),
	),
	"Block nameMembership items" => array(
		_x( "Membership items", "Block name", 'yith-woocommerce-membership' ),
	),
	"Block nameMembership downloaded product links" => array(
		_x( "Membership downloaded product links", "Block name", 'yith-woocommerce-membership' ),
	),
);